package frc.robot;

// Auto-generated by build.gradle — do not edit.
public final class BuildConstants {
    private BuildConstants() {}

    public static final String GIT_SHA = "unknown";
    public static final String BUILD_DATE = "unknown";
}
